insert into cities (name) values ('Москва');
insert into cities (name) values ('Екатеринбург');
insert into cities (name) values ('Сочи');
insert into cities (name) values ('Челябинск');
insert into cities (name) values ('Новосибирск');
insert into cities (name) values ('Санкт-Петербург');
insert into cities (name) values ('Владивосток');
insert into cities (name) values ('Оренбург');
insert into cities (name) values ('Кемерово');